import asyncio
import random
import os
from telethon import TelegramClient, events, functions, types

# Replace with your API credentials and session string
API_ID = int(os.environ.get("API_ID", "21364355"))
API_HASH = os.environ.get("API_HASH", "72f11aec1dd3e5764554d477341a3d0b")
SESSION_STRING = os.environ.get("SESSION_STRING", "")

# Replace with your desired chat ID
CHAT_ID = -1002206769379  # Example chat ID, replace with yours

Tag_messages = [
    "**Hey there,**",
    "**Hello,**",
    "**Greetings,**",
    "**Hi,**",
    "**Yo,**",
    "**Kya haal hai?**",
    "**Aur batao?**",
    "**Namaste!**",
    "**Kaise ho?**",
    "**Hey!**",
    "**Hiya,**",
    "**Sab theek?**",
    "**Milke khushi hui,**",
    "**Swagat hai,**",
    "**Kya chal raha hai?**",
    "**Hey dost,**",
    "**Hello ji,**",
    "**Tum kaise ho?**",
    "**Aap se milke accha laga,**",
    "**Ahoy!**",
    "**Dekh ke accha laga,**",
    "**Hey sab log,**",
    "**Hi sabko,**",
    "**Sab kuch kaisa hai?**",
    "**Greetings aur salutations,**",
    "**Kya ho raha hai?**",
    "**Hey logon,**",
    "**Hello duniya!**",
    "**Kaise ja raha hai?**",
    "**Accha din hai, nahi?**",
    "**Hey ajnabi,**",
    "**Hi ji,**",
    "**Tumhara din kaisa hai?**",
    "**Shubh sandhya,**",
    "**Shubh prabhat,**",
    "**Shubh dopahar,**",
    "**Hey tum,**",
    "**Kya naya hai?**",
    "**Cheezein kaisi hain?**",
    "**Hey, kaise ho?**",
    "**Hello, mere dost,**",
    "**Hi, yahan aake accha laga,**",
    "**Mausam kaisa hai?**",
    "**Hey, buddy,**",
    "**Hello, pyare logon,**",
    "**Hi, team,**",
    "**Project kaisa chal raha hai?**",
    "**Hey, tum kaisa mehsoos kar rahe ho?**",
    "**Hello, sunshine,**",
    "**Hi, swagat hai,**",
    "**Kya scene hai?**",
    "**Arre wah!**",
    "**Badiya!**",
    "**Kya baat hai?**",
    "**Sunao?**",
    "**Kahaan ho aajkal?**",
    "**Haanji!**",
    "**Aur kya chal raha hai?**",
    "**Kya planning hai?**",
    "**Aao, aao!**",
    "**Welcome ji welcome!**",
    "**Kya khabar?**",
    "**Sab raazi khushi?**",
    "**Mazaa aa gaya!**",
    "**Kya bolti public?**",
    "**Aap kaise hain?**",
    "**Theek thaak?**",
    "**Kya chal raha tha?**",
    "**Aaj kya program hai?**",
    "**Hello mere pyaare doston!**",
    "**Hi, sabko mera pyaar!**",
    "**Kya ho raha hai bhai?**",
    "**Aur bataiye?**",
    "**Kya haal chaal?**",
    "**Aapka din shubh ho!**",
    "**Hey, tumhara kya plan hai?**",
    "**Hello, sundar logon!**",
    "**Hi, yahan pe sab kaise hain?**",
    "**Kya mast din hai!**",
    "**Hey, tumhara week kaisa gaya?**",
    "**Hello, mere saathi!**",
    "**Hi, yahan aakar dil khush ho gaya!**",
    "**Kya chal raha hai yaar?**",
    "**Aur batao dost?**",
    "**Kya khabar hai bhai?**",
    "**Aapka swagat hai!**",
    "**Hey, tumhara mood kaisa hai?**",
    "**Hello, mere anmol logon!**",
    "**Hi, yahan pe sab theek hai?**",
    "**Kya shandaar din hai!**",
    "**Hey, tumhara weekend kaisa raha?**",
    "**Hello, mere pyaare saathi!**",
    "**Hi, yahan aakar bahut accha laga!**",
    "**Kya chal raha hai dost?**",
    "**Aur batao yaaron?**",
    "**Kya khabar hai yaaron?**",
    "**Aapka din mangalmay ho!**",
    "**Hey, tumhara din kaisa beet raha hai?**",
    "**Hello, mere dil ke tukdon!**",
    "**Hi, yahan pe sab khush hain?**",
    "**Kya scene hai aaj?**",
    "**Arre bhai, kya haal hai?**",
    "**Badiya chal raha hai sab?**",
    "**Kya baat, kya baat!**",
    "**Sunao toh sahi, kya chal raha hai?**",
    "**Kahaan gayab ho gaye the?**",
    "**Haanji, sab theek?**",
    "**Aur batao, kya khaas hai?**",
    "**Kya planning hai aaj ki?**",
    "**Aao, aao, welcome!**",
    "**Welcome, welcome ji!**",
    "**Kya khabar laaye ho?**",
    "**Sab raazi khushi toh hai na?**",
    "**Mazaa aa gaya sunke!**",
    "**Kya bolti public, sab theek?**",
    "**Aap kaise hain, janab?**",
    "**Theek thaak ho na?**",
    "**Kya chal raha tha, batao toh?**",
    "**Aaj kya program banaya hai?**",
    "**Hello mere pyaare mitron!**",
    "**Hi, sabko pyaar bhara namaskar!**",
    "**Kya ho raha hai, mere dost?**",
    "**Aur bataiye, kya chal raha hai?**",
    "**Kya haal chaal hai, bhai?**",
    "**Aapka din shubh aur mangalmay ho!**",
    "**Hey, tumhara kya plan hai aaj?**",
    "**Hello, sundar logon, kaise ho?**",
    "**Hi, yahan pe sab kaise hain, batao toh?**",
    "**Kya mast din hai, yaar!**",
    "**Hey, tumhara week kaisa raha, batao?**",
    "**Hello, mere saathi, kya haal hai?**",
    "**Hi, yahan aakar dil khush ho gaya, bhai!**",
    "**Kya chal raha hai, mere pyaare dost?**",
    "**Aur batao, mere yaaron?**",
    "**Kya khabar hai, mere yaaron?**",
    "**Aapka din mangalmay ho, bhagwan kare!**",
    "**Hey, tumhara din kaisa beet raha hai, batao?**",
    "**Hello, mere dil ke tukdon, kaise ho?**",
    "**Hi, yahan pe sab khush hain na?**",
    "**Kya shandaar din hai, wah!**",
    "**Hey, tumhara weekend kaisa raha, sunao?**",
    "**Hello, mere pyaare saathiyon!**",
    "**Hi, yahan aakar bahut accha laga, bhai!**",
    "**Kya chal raha hai, mere dost?**",
    "**Aur batao, mere yaaron?**",
    "**Kya khabar hai, mere yaaron?**",
    "**Aapka din mangalmay ho, prabhu kare!**",
    "**Hey, tumhara din kaisa beet raha hai, yaar?**",
    "**Hello, mere dil ke tukdon, kya haal hai?**",
    "**Hi, yahan pe sab khush hain na, batao?**",
    "**Kya naya samaachaar hai?**",
    "**Kaisa lag raha hai aaj?**",
    "**Kya programme hai?**",
    "**Aapka swagat hai, shree maan!**",
    "**Kya baat hai, bhai!**",
    "**Sunao, kya chal raha hai?**",
    "**Kahaan ho aaj kal, mitr?**",
    "**Haanji, sab theek hai na?**",
    "**Aur batao, kya vishesh hai?**",
    "**Kya planning hai aaj ke liye?**",
    "**Aao, aao, swagat hai!**",
    "**Welcome ji, welcome!**",
    "**Kya khabar lekar aaye ho?**",
    "**Sab raazi khushi hai na?**",
    "**Mazaa aa gaya sunkar!**",
    "**Kya bolti public, sab theek thaak?**",
    "**Aap kaise hain, mahoday?**",
    "**Theek thaak ho na, bhai?**",
    "**Kya chal raha tha, batao toh sahi?**",
    "**Aaj kya karyakram hai?**",
    "**Hello mere pyaare mitron aur saheliyon!**",
    "**Hi, sabko prem bhara namaskar!**",
    "**Kya ho raha hai, mere param mitra?**",
    "**Aur bataiye, kya samachaar hai?**",
    "**Kya haal chaal hai, mere dost?**",
    "**Aapka din shubh aur mangalmay rahe!**",
    "**Hey, tumhara kya plan hai aaj ke liye?**",
    "**Hello, sundar logon, kaise hain aap sab?**",
    "**Hi, yahan pe sab kaise hain, kripya bataiye?**",
    "**Kya mast din hai, mere dost!**",
    "**Hey, tumhara week kaisa raha, kripya bataiye?**",
    "**Hello, mere saathi, kya haal chaal hain?**",
    "**Hi, yahan aakar dil khush ho gaya, mere bhai!**",
    "**Kya chal raha hai, mere pyaare mitr?**",
    "**Aur batao, mere yaaron aur saheliyon?**",
    "**Kya khabar hai, mere yaaron aur mitron?**",
    "**Aapka din mangalmay ho, bhagwan ki kripa se!**",
    "**Hey, tumhara din kaisa beet raha hai, mere dost?**",
    "**Hello, mere dil ke tukdon, kya haal chaal hain?**",
    "**Hi, yahan pe sab khush hain na, kripya bataiye?**",
    "**Kya shandaar din hai, wah wah!**",
    "**Hey, tumhara weekend kaisa raha, kripya sunao?**",
    "**Hello, mere pyaare saathiyon aur saheliyon!**",
    "**Hi, yahan aakar bahut accha laga, mere bhaiyon aur behnon!**",
    "**Kya chal raha hai, mere dost aur mitr?**",
    "**Aur batao, mere yaaron aur saheliyon!**",
    "**Kya khabar hai, mere yaaron aur mitron?**",
    "**Aapka din mangalmay ho, prabhu ki kripa se!**",
    "**Hey, tumhara din kaisa beet raha hai, mere mitr?**",
    "**Hello, mere dil ke tukdon, kya haal chaal hain?**",
    "**Hi, yahan pe sab khush hain na, kripya bataiye!**"
]

Emojis = [
          "😀", "🎉", "🥳", "✨", "😊", "👍", "👋", "😎", "🤩", "👏",
          "😂", "❤️", "🙏", "😭", "😍", "🤣", "🥰", "😇", "🥳", "🤩",
          "😋", "😜", "🤪", "😝", "🤑", "🤗", "🤔", "🤫", "🤭", "🤐",
          "🤨", "😐", "😑", "😶", "🙄", "😏", "😒", "🤥", "😌", "🤤",
          "😴", "😷", "🤒", "🤕", "🤢", "🤮", "🤧", "🥵", "🥶", "🥴",
          "🤯", "🤠", "🥳", "🥸", "🥺", "🐶", "🐱", "🐭", "🐹", "🐰",
          "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐸", "🐵",
          "🐔", "🐧", "🐦", "🐤", "🦆", "🦅", "🦉", "🦇", "🦋", "🐛",
          "🐜", "🐝", "🐞", "🐢", "🐍", "🦎", "🦀", "🦞", "🦐", "🦑",
          "🐙", "🐟", "🐠", "🐡", "🐬", "🐳", "🐋", "🐊", "🐅", "🐆",
          "🦓","🦍", "🦧"
]

client = TelegramClient(SESSION_STRING, API_ID, API_HASH)

async def tag_online_members():
    try:
        async for participant in client.iter_participants(CHAT_ID, filter=types.ChannelParticipantsOnline):
            if not participant.bot:
                message = f"{participant.mention} {random.choice(Tag_messages)} {random.choice(Emojis)}"
                await client.send_message(CHAT_ID, message)
                await asyncio.sleep(1.5)  # Delay between tags (adjust as needed)
    except Exception as e:
        print(f"Error during tagging: {e}")

@client.on(events.NewMessage(pattern=r"^/gm$", from_users='me'))
async def start_tagging(event):
    await event.respond("Tagging online members...")
    await tag_online_members()
    await event.respond("@MrSameerXD nibba khi ka!")

async def main():
    await client.start()
    print("Client started. Running...")
    await client.run_until_disconnected()

if __name__ == "__main__":
    asyncio.run(main())
